field_width: 40
grid_height: 16
org_cols: 3
genome_rows: 16
birth: [3]
survival: [2, 3]
near_birth: [3]
near_survival: [2, 3]
mutation_rate: 0.005
crossover: false
population_size: 100
games_per_round: 20
n_rounds: 25
steps_per_game: 300
save_gifs_interval: 10
